[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cliptzy"
version = "2.0.7"
description = "Cliptzy Desktop Standalone"
readme = "README.md"
authors = [
    { name = "Dicky Mulia Fiqri", email = "santrialanwari@gmail.com" }
]
requires-python = ">=3.13"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.in"]}

[project.scripts]
cliptzy = "main:main"

[tool.flet]
exclude = [
    ".git",
    ".github",
    ".venv",
    "clips",
    "logs",
    "venv",
    "__pycache__",
    "cred/supabase_session.json",
    "*.log"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["core", "gui", "fonts", "assets"]
exclude = []
namespaces = false

[tool.flet.macos]
target_arch = ["x86_64"]