[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cliptzy"
version = "3.0.15"
description = "Cliptzy Desktop Standalone"
readme = "README.md"
authors = [
    { name = "Dicky Mulia Fiqri", email = "santrialanwari@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "yt-dlp",
    "faster-whisper",
    "instagrapi",
    "supabase",
    "python-dotenv",
    "google-genai",
    "google-api-python-client",
    "google-auth-oauthlib",
    "gTTS",
    "psutil",
    "requests",
    "playwright",
    "openai",
    "opencv-python-headless",
    "edge-tts",
    "flet",
    "flet-video",
    "flet-audio",
    "pystray",
    "desktop-notifier",
    "certifi",
    "tiktok-uploader @ git+https://github.com/dickymuliafiqri/tiktok-uploader",
    "deepface",
    "tf-keras",
    "torch",
    "torchaudio",
    "lazy-loader",
    "soxr",
    "transformers",
    "tokenizers",
    "librosa",
    "setuptools<70.0.0",
    "retina-face>=0.0.18",
    "kokoro>=0.9.4",
    "soundfile>=0.14.0",
]

[project.scripts]
cliptzy = "main:main"

[tool.flet.app]
module = "main.main"
name = "Cliptzy"
description = "YouTube Clipper & Auto Uploader"
exclude = [
    ".git",
    ".github",
    ".venv",
    "clips",
    "logs",
    "venv",
    "__pycache__",
    "cred",
    "*.json",
    "*.log",
    ".env",
    "*.md",
    "comments.txt",
    "tests",
    "*.sql",
    ".gitignore"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["core", "gui", "fonts", "assets"]
exclude = []
namespaces = false

[tool.flet.macos]
target_arch = ["x86_64"]

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = [
    ".venv",
    ".flet",
    "__pycache__",
    "build",
    "dist",
    "clips",
    "temp",
    "bin"
]
